//#region AUTH
export const SIGNIN_PENDING = 'SIGNIN_PENDING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_REJECT = 'SIGNIN_REJECT';

export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_REJECT = 'SIGNUP_REJECT';

export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_REJECT = 'AUTH_REJECT';

export const CLEAN_ERRORS = 'CLEAN_ERRORS';
export const LOGOUT = 'LOGOUT';
//#endregion

//#region LISTING
export const REQUEST_PHOTOS_PENDING = "REQUEST_PHOTOS_PENDING";
export const REQUEST_PHOTOS_SUCCESS = "REQUEST_PHOTOS_SUCCESS";
export const REQUEST_PHOTOS_REJECT = "REQUEST_PHOTOS_REJECT";

export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCESS = "REQUEST_POSTS_SUCCESS";
export const REQUEST_POSTS_REJECT = "REQUEST_POSTS_REJECT";
//#endregion